/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.todo.list.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.todo.list.model.SubTask;
import com.todo.list.model.SubTaskModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SubTask service. Represents a row in the &quot;Todo_SubTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SubTaskModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubTaskImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubTaskImpl
 * @generated
 */
public class SubTaskModelImpl
	extends BaseModelImpl<SubTask> implements SubTaskModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sub task model instance should use the <code>SubTask</code> interface instead.
	 */
	public static final String TABLE_NAME = "Todo_SubTask";

	public static final Object[][] TABLE_COLUMNS = {
		{"subTaskId", Types.BIGINT}, {"taskId", Types.BIGINT},
		{"title", Types.VARCHAR}, {"completed", Types.BOOLEAN},
		{"deleted", Types.BOOLEAN}, {"position", Types.INTEGER},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("subTaskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("taskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("completed", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("deleted", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("position", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Todo_SubTask (subTaskId LONG not null primary key,taskId LONG,title VARCHAR(75) null,completed BOOLEAN,deleted BOOLEAN,position INTEGER,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Todo_SubTask";

	public static final String ORDER_BY_JPQL =
		" ORDER BY subTask.subTaskId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Todo_SubTask.subTaskId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DELETED_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TASKID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBTASKID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.todo.com.todo.list.service.util.ServiceProps.get(
			"lock.expiration.time.com.todo.list.model.SubTask"));

	public SubTaskModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _subTaskId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubTaskId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subTaskId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SubTask.class;
	}

	@Override
	public String getModelClassName() {
		return SubTask.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SubTask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SubTask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubTask, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SubTask)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SubTask, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SubTask, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SubTask)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SubTask, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SubTask, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<SubTask, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<SubTask, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<SubTask, Object>>();

			attributeGetterFunctions.put("subTaskId", SubTask::getSubTaskId);
			attributeGetterFunctions.put("taskId", SubTask::getTaskId);
			attributeGetterFunctions.put("title", SubTask::getTitle);
			attributeGetterFunctions.put("completed", SubTask::getCompleted);
			attributeGetterFunctions.put("deleted", SubTask::getDeleted);
			attributeGetterFunctions.put("position", SubTask::getPosition);
			attributeGetterFunctions.put("createDate", SubTask::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", SubTask::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<SubTask, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SubTask, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SubTask, ?>>();

			attributeSetterBiConsumers.put(
				"subTaskId", (BiConsumer<SubTask, Long>)SubTask::setSubTaskId);
			attributeSetterBiConsumers.put(
				"taskId", (BiConsumer<SubTask, Long>)SubTask::setTaskId);
			attributeSetterBiConsumers.put(
				"title", (BiConsumer<SubTask, String>)SubTask::setTitle);
			attributeSetterBiConsumers.put(
				"completed",
				(BiConsumer<SubTask, Boolean>)SubTask::setCompleted);
			attributeSetterBiConsumers.put(
				"deleted", (BiConsumer<SubTask, Boolean>)SubTask::setDeleted);
			attributeSetterBiConsumers.put(
				"position", (BiConsumer<SubTask, Integer>)SubTask::setPosition);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<SubTask, Date>)SubTask::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<SubTask, Date>)SubTask::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getSubTaskId() {
		return _subTaskId;
	}

	@Override
	public void setSubTaskId(long subTaskId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subTaskId = subTaskId;
	}

	@Override
	public long getTaskId() {
		return _taskId;
	}

	@Override
	public void setTaskId(long taskId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_taskId = taskId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTaskId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("taskId"));
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public boolean getCompleted() {
		return _completed;
	}

	@Override
	public boolean isCompleted() {
		return _completed;
	}

	@Override
	public void setCompleted(boolean completed) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_completed = completed;
	}

	@Override
	public boolean getDeleted() {
		return _deleted;
	}

	@Override
	public boolean isDeleted() {
		return _deleted;
	}

	@Override
	public void setDeleted(boolean deleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deleted = deleted;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalDeleted() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("deleted"));
	}

	@Override
	public int getPosition() {
		return _position;
	}

	@Override
	public void setPosition(int position) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_position = position;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SubTask.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SubTask toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SubTask>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubTaskImpl subTaskImpl = new SubTaskImpl();

		subTaskImpl.setSubTaskId(getSubTaskId());
		subTaskImpl.setTaskId(getTaskId());
		subTaskImpl.setTitle(getTitle());
		subTaskImpl.setCompleted(isCompleted());
		subTaskImpl.setDeleted(isDeleted());
		subTaskImpl.setPosition(getPosition());
		subTaskImpl.setCreateDate(getCreateDate());
		subTaskImpl.setModifiedDate(getModifiedDate());

		subTaskImpl.resetOriginalValues();

		return subTaskImpl;
	}

	@Override
	public SubTask cloneWithOriginalValues() {
		SubTaskImpl subTaskImpl = new SubTaskImpl();

		subTaskImpl.setSubTaskId(
			this.<Long>getColumnOriginalValue("subTaskId"));
		subTaskImpl.setTaskId(this.<Long>getColumnOriginalValue("taskId"));
		subTaskImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		subTaskImpl.setCompleted(
			this.<Boolean>getColumnOriginalValue("completed"));
		subTaskImpl.setDeleted(this.<Boolean>getColumnOriginalValue("deleted"));
		subTaskImpl.setPosition(
			this.<Integer>getColumnOriginalValue("position"));
		subTaskImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		subTaskImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return subTaskImpl;
	}

	@Override
	public int compareTo(SubTask subTask) {
		long primaryKey = subTask.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SubTask)) {
			return false;
		}

		SubTask subTask = (SubTask)object;

		long primaryKey = subTask.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SubTask> toCacheModel() {
		SubTaskCacheModel subTaskCacheModel = new SubTaskCacheModel();

		subTaskCacheModel.subTaskId = getSubTaskId();

		subTaskCacheModel.taskId = getTaskId();

		subTaskCacheModel.title = getTitle();

		String title = subTaskCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			subTaskCacheModel.title = null;
		}

		subTaskCacheModel.completed = isCompleted();

		subTaskCacheModel.deleted = isDeleted();

		subTaskCacheModel.position = getPosition();

		Date createDate = getCreateDate();

		if (createDate != null) {
			subTaskCacheModel.createDate = createDate.getTime();
		}
		else {
			subTaskCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			subTaskCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			subTaskCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return subTaskCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SubTask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SubTask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubTask, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SubTask)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SubTask>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SubTask.class, ModelWrapper.class);

	}

	private long _subTaskId;
	private long _taskId;
	private String _title;
	private boolean _completed;
	private boolean _deleted;
	private int _position;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<SubTask, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SubTask)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("subTaskId", _subTaskId);
		_columnOriginalValues.put("taskId", _taskId);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("completed", _completed);
		_columnOriginalValues.put("deleted", _deleted);
		_columnOriginalValues.put("position", _position);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("subTaskId", 1L);

		columnBitmasks.put("taskId", 2L);

		columnBitmasks.put("title", 4L);

		columnBitmasks.put("completed", 8L);

		columnBitmasks.put("deleted", 16L);

		columnBitmasks.put("position", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SubTask _escapedModel;

}