/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.todo.list.model.impl;

import com.todo.list.model.SubTask;
import com.todo.list.service.SubTaskLocalServiceUtil;

/**
 * The extended model base implementation for the SubTask service. Represents a row in the &quot;Todo_SubTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubTaskImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubTaskImpl
 * @see SubTask
 * @generated
 */
public abstract class SubTaskBaseImpl
	extends SubTaskModelImpl implements SubTask {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sub task model instance should use the <code>SubTask</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SubTaskLocalServiceUtil.addSubTask(this);
		}
		else {
			SubTaskLocalServiceUtil.updateSubTask(this);
		}
	}

}