/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.todo.list.model.impl;

import com.todo.list.model.TaskAttachment;
import com.todo.list.service.TaskAttachmentLocalServiceUtil;

/**
 * The extended model base implementation for the TaskAttachment service. Represents a row in the &quot;Todo_TaskAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskAttachmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskAttachmentImpl
 * @see TaskAttachment
 * @generated
 */
public abstract class TaskAttachmentBaseImpl
	extends TaskAttachmentModelImpl implements TaskAttachment {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a task attachment model instance should use the <code>TaskAttachment</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TaskAttachmentLocalServiceUtil.addTaskAttachment(this);
		}
		else {
			TaskAttachmentLocalServiceUtil.updateTaskAttachment(this);
		}
	}

}