/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.todo.list.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.todo.list.model.TaskAttachment;
import com.todo.list.model.TaskAttachmentModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TaskAttachment service. Represents a row in the &quot;Todo_TaskAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TaskAttachmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskAttachmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskAttachmentImpl
 * @generated
 */
public class TaskAttachmentModelImpl
	extends BaseModelImpl<TaskAttachment> implements TaskAttachmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a task attachment model instance should use the <code>TaskAttachment</code> interface instead.
	 */
	public static final String TABLE_NAME = "Todo_TaskAttachment";

	public static final Object[][] TABLE_COLUMNS = {
		{"taskAttachmentId", Types.BIGINT}, {"taskId", Types.BIGINT},
		{"fileEntryId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"deleted", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("taskAttachmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("taskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("deleted", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Todo_TaskAttachment (taskAttachmentId LONG not null primary key,taskId LONG,fileEntryId LONG,createDate DATE null,modifiedDate DATE null,deleted BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table Todo_TaskAttachment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY taskAttachment.taskAttachmentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Todo_TaskAttachment.taskAttachmentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DELETED_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TASKID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TASKATTACHMENTID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.todo.com.todo.list.service.util.ServiceProps.get(
			"lock.expiration.time.com.todo.list.model.TaskAttachment"));

	public TaskAttachmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taskAttachmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaskAttachmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taskAttachmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaskAttachment.class;
	}

	@Override
	public String getModelClassName() {
		return TaskAttachment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TaskAttachment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TaskAttachment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskAttachment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TaskAttachment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TaskAttachment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TaskAttachment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TaskAttachment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TaskAttachment, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TaskAttachment, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<TaskAttachment, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<TaskAttachment, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<TaskAttachment, Object>>();

			attributeGetterFunctions.put(
				"taskAttachmentId", TaskAttachment::getTaskAttachmentId);
			attributeGetterFunctions.put("taskId", TaskAttachment::getTaskId);
			attributeGetterFunctions.put(
				"fileEntryId", TaskAttachment::getFileEntryId);
			attributeGetterFunctions.put(
				"createDate", TaskAttachment::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", TaskAttachment::getModifiedDate);
			attributeGetterFunctions.put("deleted", TaskAttachment::getDeleted);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<TaskAttachment, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<TaskAttachment, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<TaskAttachment, ?>>();

			attributeSetterBiConsumers.put(
				"taskAttachmentId",
				(BiConsumer<TaskAttachment, Long>)
					TaskAttachment::setTaskAttachmentId);
			attributeSetterBiConsumers.put(
				"taskId",
				(BiConsumer<TaskAttachment, Long>)TaskAttachment::setTaskId);
			attributeSetterBiConsumers.put(
				"fileEntryId",
				(BiConsumer<TaskAttachment, Long>)
					TaskAttachment::setFileEntryId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<TaskAttachment, Date>)
					TaskAttachment::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<TaskAttachment, Date>)
					TaskAttachment::setModifiedDate);
			attributeSetterBiConsumers.put(
				"deleted",
				(BiConsumer<TaskAttachment, Boolean>)
					TaskAttachment::setDeleted);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getTaskAttachmentId() {
		return _taskAttachmentId;
	}

	@Override
	public void setTaskAttachmentId(long taskAttachmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_taskAttachmentId = taskAttachmentId;
	}

	@Override
	public long getTaskId() {
		return _taskId;
	}

	@Override
	public void setTaskId(long taskId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_taskId = taskId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTaskId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("taskId"));
	}

	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public boolean getDeleted() {
		return _deleted;
	}

	@Override
	public boolean isDeleted() {
		return _deleted;
	}

	@Override
	public void setDeleted(boolean deleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deleted = deleted;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalDeleted() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("deleted"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, TaskAttachment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaskAttachment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TaskAttachment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaskAttachmentImpl taskAttachmentImpl = new TaskAttachmentImpl();

		taskAttachmentImpl.setTaskAttachmentId(getTaskAttachmentId());
		taskAttachmentImpl.setTaskId(getTaskId());
		taskAttachmentImpl.setFileEntryId(getFileEntryId());
		taskAttachmentImpl.setCreateDate(getCreateDate());
		taskAttachmentImpl.setModifiedDate(getModifiedDate());
		taskAttachmentImpl.setDeleted(isDeleted());

		taskAttachmentImpl.resetOriginalValues();

		return taskAttachmentImpl;
	}

	@Override
	public TaskAttachment cloneWithOriginalValues() {
		TaskAttachmentImpl taskAttachmentImpl = new TaskAttachmentImpl();

		taskAttachmentImpl.setTaskAttachmentId(
			this.<Long>getColumnOriginalValue("taskAttachmentId"));
		taskAttachmentImpl.setTaskId(
			this.<Long>getColumnOriginalValue("taskId"));
		taskAttachmentImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		taskAttachmentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		taskAttachmentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		taskAttachmentImpl.setDeleted(
			this.<Boolean>getColumnOriginalValue("deleted"));

		return taskAttachmentImpl;
	}

	@Override
	public int compareTo(TaskAttachment taskAttachment) {
		long primaryKey = taskAttachment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TaskAttachment)) {
			return false;
		}

		TaskAttachment taskAttachment = (TaskAttachment)object;

		long primaryKey = taskAttachment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TaskAttachment> toCacheModel() {
		TaskAttachmentCacheModel taskAttachmentCacheModel =
			new TaskAttachmentCacheModel();

		taskAttachmentCacheModel.taskAttachmentId = getTaskAttachmentId();

		taskAttachmentCacheModel.taskId = getTaskId();

		taskAttachmentCacheModel.fileEntryId = getFileEntryId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			taskAttachmentCacheModel.createDate = createDate.getTime();
		}
		else {
			taskAttachmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			taskAttachmentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			taskAttachmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		taskAttachmentCacheModel.deleted = isDeleted();

		return taskAttachmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TaskAttachment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TaskAttachment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskAttachment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TaskAttachment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TaskAttachment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TaskAttachment.class, ModelWrapper.class);

	}

	private long _taskAttachmentId;
	private long _taskId;
	private long _fileEntryId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _deleted;

	public <T> T getColumnValue(String columnName) {
		Function<TaskAttachment, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TaskAttachment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("taskAttachmentId", _taskAttachmentId);
		_columnOriginalValues.put("taskId", _taskId);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("deleted", _deleted);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("taskAttachmentId", 1L);

		columnBitmasks.put("taskId", 2L);

		columnBitmasks.put("fileEntryId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("deleted", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TaskAttachment _escapedModel;

}