# Configurações do PostgreSQL
jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.url=jdbc:postgresql://postgres:5432/liferay_todo
jdbc.default.username=liferay
jdbc.default.password=liferay

# Pula aquela tela inicial chata de configuração do Liferay
setup.wizard.enabled=false