/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.todo.list.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SubTask service. Represents a row in the &quot;Todo_SubTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.todo.list.model.impl.SubTaskModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.todo.list.model.impl.SubTaskImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubTask
 * @generated
 */
@ProviderType
public interface SubTaskModel extends BaseModel<SubTask> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sub task model instance should use the {@link SubTask} interface instead.
	 */

	/**
	 * Returns the primary key of this sub task.
	 *
	 * @return the primary key of this sub task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sub task.
	 *
	 * @param primaryKey the primary key of this sub task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sub task ID of this sub task.
	 *
	 * @return the sub task ID of this sub task
	 */
	public long getSubTaskId();

	/**
	 * Sets the sub task ID of this sub task.
	 *
	 * @param subTaskId the sub task ID of this sub task
	 */
	public void setSubTaskId(long subTaskId);

	/**
	 * Returns the task ID of this sub task.
	 *
	 * @return the task ID of this sub task
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this sub task.
	 *
	 * @param taskId the task ID of this sub task
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the title of this sub task.
	 *
	 * @return the title of this sub task
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this sub task.
	 *
	 * @param title the title of this sub task
	 */
	public void setTitle(String title);

	/**
	 * Returns the completed of this sub task.
	 *
	 * @return the completed of this sub task
	 */
	public boolean getCompleted();

	/**
	 * Returns <code>true</code> if this sub task is completed.
	 *
	 * @return <code>true</code> if this sub task is completed; <code>false</code> otherwise
	 */
	public boolean isCompleted();

	/**
	 * Sets whether this sub task is completed.
	 *
	 * @param completed the completed of this sub task
	 */
	public void setCompleted(boolean completed);

	/**
	 * Returns the deleted of this sub task.
	 *
	 * @return the deleted of this sub task
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this sub task is deleted.
	 *
	 * @return <code>true</code> if this sub task is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this sub task is deleted.
	 *
	 * @param deleted the deleted of this sub task
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the position of this sub task.
	 *
	 * @return the position of this sub task
	 */
	public int getPosition();

	/**
	 * Sets the position of this sub task.
	 *
	 * @param position the position of this sub task
	 */
	public void setPosition(int position);

	/**
	 * Returns the create date of this sub task.
	 *
	 * @return the create date of this sub task
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this sub task.
	 *
	 * @param createDate the create date of this sub task
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sub task.
	 *
	 * @return the modified date of this sub task
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sub task.
	 *
	 * @param modifiedDate the modified date of this sub task
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public SubTask cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}