/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.todo.list.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TaskAttachment service. Represents a row in the &quot;Todo_TaskAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.todo.list.model.impl.TaskAttachmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.todo.list.model.impl.TaskAttachmentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskAttachment
 * @generated
 */
@ProviderType
public interface TaskAttachmentModel extends BaseModel<TaskAttachment> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task attachment model instance should use the {@link TaskAttachment} interface instead.
	 */

	/**
	 * Returns the primary key of this task attachment.
	 *
	 * @return the primary key of this task attachment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task attachment.
	 *
	 * @param primaryKey the primary key of this task attachment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task attachment ID of this task attachment.
	 *
	 * @return the task attachment ID of this task attachment
	 */
	public long getTaskAttachmentId();

	/**
	 * Sets the task attachment ID of this task attachment.
	 *
	 * @param taskAttachmentId the task attachment ID of this task attachment
	 */
	public void setTaskAttachmentId(long taskAttachmentId);

	/**
	 * Returns the task ID of this task attachment.
	 *
	 * @return the task ID of this task attachment
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this task attachment.
	 *
	 * @param taskId the task ID of this task attachment
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the file entry ID of this task attachment.
	 *
	 * @return the file entry ID of this task attachment
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this task attachment.
	 *
	 * @param fileEntryId the file entry ID of this task attachment
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the create date of this task attachment.
	 *
	 * @return the create date of this task attachment
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this task attachment.
	 *
	 * @param createDate the create date of this task attachment
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this task attachment.
	 *
	 * @return the modified date of this task attachment
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task attachment.
	 *
	 * @param modifiedDate the modified date of this task attachment
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the deleted of this task attachment.
	 *
	 * @return the deleted of this task attachment
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this task attachment is deleted.
	 *
	 * @return <code>true</code> if this task attachment is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this task attachment is deleted.
	 *
	 * @param deleted the deleted of this task attachment
	 */
	public void setDeleted(boolean deleted);

	@Override
	public TaskAttachment cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}